
CREATE TABLE EMPLOYEES (
ID NUMBER(4) primary key,
First_Name VARCHAR2(30),
Last_Name VARCHAR2(30),
MobileNo NUMBER(8),
Salary NUMBER(9,2)
);

--ID Auto Increment using TRIGGER
CREATE SEQUENCE emp_seq START WITH 1;
CREATE OR REPLACE TRIGGER emp_bir 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW
BEGIN
  SELECT emp_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;

--DROP TRIGGER emp_bir; 

CREATE OR REPLACE PROCEDURE sp_getEmpById 
   (EMP_ID IN NUMBER, EMP_First_Name OUT VARCHAR2, EMP_Last_Name OUT VARCHAR2, EMP_MobileNo OUT NUMBER, EMP_Salary OUT NUMBER) AS
BEGIN
   SELECT First_Name, Last_Name, MobileNo, Salary INTO EMP_First_Name, EMP_Last_Name, EMP_MobileNo, EMP_Salary
   FROM EMPLOYEES
   WHERE ID = EMP_ID;
END;

CREATE OR REPLACE PROCEDURE sp_addEmp 
   (EMP_First_Name IN VARCHAR2, EMP_Last_Name IN VARCHAR2, EMP_MobileNo IN NUMBER, EMP_Salary IN NUMBER) AS
BEGIN
   INSERT INTO EMPLOYEES (First_Name,Last_Name,MobileNo,Salary) VALUES (EMP_First_Name,EMP_Last_Name,EMP_MobileNo,EMP_Salary);
END;

CREATE OR REPLACE PROCEDURE sp_updateEmp 
   (EMP_ID IN NUMBER, EMP_First_Name IN VARCHAR2, EMP_Last_Name IN VARCHAR2, EMP_MobileNo IN NUMBER, EMP_Salary IN NUMBER) AS
BEGIN
   UPDATE EMPLOYEES SET First_Name = EMP_FIRST_NAME, Last_Name = EMP_LAST_NAME, MobileNo = EMP_MobileNo, Salary = EMP_SALARY WHERE ID = EMP_ID;
END;

CREATE OR REPLACE PROCEDURE sp_deleteEmp 
   (EMP_ID IN NUMBER) AS
BEGIN
   DELETE FROM EMPLOYEES WHERE ID = EMP_ID;
END;

--DROP PROCEDURE sp_name;

SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES READ WRITE;
